---
- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install default packages
  ansible.builtin.apt:
    pkg: 
    - python3-venv
    - python3-dev
    - python3-pip
    - vim
    - git
  become: true
